PET_WIDTH = 65
PET_HEIGHT = 65
PET_MOVIE_PATH = "Assets/bee/bee_fly_2.gif"


CHAT_WIN_OFFSET_X = -125
CHAT_WIN_OFFSET_Y = -370

MOVEMENT_X_MIN_RATIO = 0.0
MOVEMENT_X_MAX_RATIO = 1.0
MOVEMENT_Y_MIN_RATIO = 0.0
MOVEMENT_Y_MAX_RATIO = 1.0
